// Generated by CoffeeScript 1.3.1
(function() {
  var root, surrogateUrl;

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.surrogate = {};

  surrogateUrl = 'http://10.11.108.249:8002';

  surrogate.compileLatex = function(path, owner) {
    var data;
    data = {};
    data = {
      'host': webfs.info.hostname,
      'port': webfs.info.port,
      'path': path,
      'owner': owner
    };
    return $.ajax({
      type: 'POST',
      url: surrogateUrl + '/checkout',
      data: JSON.stringify(data),
      contentTypeString: 'application/json',
      success: function(data) {
        return console.log(data);
      }
    });
  };

}).call(this);
